### ISSUE TITLE
Add descriptions to github All Projects section

### ISSUE THREAD

**Issue by feydan** [code4sac/codeforsacramento.org#63]
Under the All Projects section on http://codeforsacramento.org/projects/, it would be great to pull the description section of the github repo into the content.

**Comment by joelbarker2011** [comment]
- This is already implemented: https://github.com/code4sac/codeforsacramento.org/blob/gh-pages/projects/index.html#L58

- The problem is that most projects don't have descriptions in GitHub currently. If they do, they will show up. See the `openbudgetsac.org` project, for example.

- I don't see any other metadata that is comparable to the `description` field. For example:
```json
    {
      "api_url": "http://api.codeforamerica.org/api/projects/67268",
      "categories": null,
      "code_url": "https://github.com/code4sac/ndoch-asset-map-python",
      "commit_status": "pending",
      "description": null,
      "github_details": {
        "contributors": [],
        "contributors_url": "https://api.github.com/repos/code4sac/ndoch-asset-map-python/contributors",
        "created_at": "2020-08-27T02:19:02Z",
        "description": null,
        "forks_count": 1,
        "homepage": null,
        "html_url": "https://github.com/code4sac/ndoch-asset-map-python",
        "id": 290652848,
        "name": "ndoch-asset-map-python",
        "open_issues": 0,
        "owner": {
          "avatar_url": "https://avatars.githubusercontent.com/u/3915088?v=4",
          "html_url": "https://github.com/code4sac",
          "login": "code4sac",
          "type": "Organization"
        },
        "participation": [ ... ],
        "pushed_at": "2020-09-10T02:10:27Z",
        "stargazers_count": 0,
        "subscribers_count": 8,
        "updated_at": "2020-09-10T02:10:33Z",
        "watchers_count": 0
      },
      "id": 67268,
      "issues": [],
      "languages": [
        "Python",
        "Jupyter Notebook",
        "HTML"
      ],
      "last_updated": "Thu, 10 Sep 2020 02:10:27 GMT",
      "link_url": null,
      "name": "ndoch-asset-map-python",
      "organization": { ... },
      "organization_name": "Code for Sacramento",
      "status": null,
      "tags": null,
      "type": null
    }
```

- Attached a patch file (renamed to `.txt` since GH does not allow unusual filename extensions) [0001-Highlight-projects-that-are-missing-GH-descriptions.patch.txt](https://github.com/code4sac/codeforsacramento.org/files/8051955/0001-Highlight-projects-that-are-missing-GH-descriptions.patch.txt) to highlight missing description. (Not a solution, but it makes the problem obvious by showing, in red, `Description is missing!`)

- I believe it will require members with admin permissions to set the descriptions on each repo.
